server:
  port: 8001

spring:
  rabbitmq:
    host: 192.168.2.140
    username: guest
    password: guest

# 配置
ali:
  AccessKeyId: LTAI4FibViPiJ6qK6916PHkp
  AccessKeySecret: M2tK5gOOjgxZQ3fqKp8yrulKiuks24
  signName: 鲍森问答论坛
  templateCode: SMS_181866518